name: Pipeline Demo CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  sonar_teste:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  qualidade:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Ambiente Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'


      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Análise Estática (Linter)
        run: flake8 .
        

      - name: Teste unitários e cobertura minima
        run: pytest --cov=app --cov-fail-under=90
  
  build-docker:
    needs: qualidade
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Login é necessário para enviar a imagem para o Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build com Docker Compose
        run: docker compose build

      - name: Push com Docker Compose
        run: docker compose push

      # Docker faz npm install e configura o ambiente sozinho
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pipeline-ci:latest

  test-docker:
    needs: build-docker
    runs-on: ubuntu-latest # Não precisa masi de Windows e MacOS, pois o container é multiplataforma
    steps:
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Ao inves de unzip e setup-node, você só chama a imagem pronta
      - name: Rodar testes dentro do Container
        run: docker run ${{ secrets.DOCKER_USER }}/pipeline-ci:latest pytest

  test-Compose-Docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Subir Ambiente de Teste
        run: docker compose up -d

      - name: Validar Comunicação (Ping)
        run: docker compose exec -T calculadora-app ping -c 1 servico-vizinho

  deploy:
    needs: [test-docker]
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Deploy Enviado"